image: node:latest

before_script:
  - npm i yarn

stages:
  - Build
  - Test
  - Deploy

before_script:
  - echo "starting...""
  - node -v

cache:
  paths:
    - node_modules/

build:
  stage: Build
  before_script:
    - yarn install
  script:
    - yarn build
  tags:
    - build

test:
  stage: Test
  before_script:
    - yarn install
  script:
    - yarn analyze
  tags:
    - test