image: node:latest

before_script:
  - npm i yarn

stages:
  - Build
  - Test
  - Deploy

before_script:
  - echo "starting...""
  - node -v

build:
  stage: Build
  before_script:
    - yarn install
  script:
    - yarn build
  tags:
    - build

test:
  stage: Test
  before_script:
    - yarn install
  script:
    - yarn analyze
  tags:
    - test

deploy:
  stage: Deploy
  before_script:
    - yarn install
  script:
    - yarn start
  tags:
    - deploy