stages:
  - Build
  - Test
  - Deploy

before_script:
  - echo "starting...""
  - node -v

build:
  stage: Build
  image: 'node:lts'
  before_script:
    - yarn install
  script:
    - yarn run build

test:
  stage: Test
  image: 'node:lts'
  before_script:
    - yarn install
  script:
    - yarn analyze

deploy:
  stage: Deploy
  image: 'node:lts'
  before_script:
    - yarn install
  script:
    - yarn start